# Generated by Django 3.2.6 on 2022-03-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='download.png', upload_to='profile_image'),
        ),
    ]
